### ISSUE TITLE
Dispose method

### ISSUE THREAD

**Issue by lucax88x** [lazytanuki/nvim-mapper#14]
Hey, thanks for the plugin, been using it.

is there any way to dispose the maps?

I have a reload function for lua modules, so I can reload my nvim, but I cannot dispose maps and reload them as they will give key conflicts.

**Comment by lazytanuki** [comment]
Hi there !

The plugin uses a global vim variable to set a table of the mappings (`vim.g.mapper_records`). Maybe setting it to `nil` would fit your use case ?

**Comment by lucax88x** [comment]
Thanks!
