### ISSUE TITLE
Additional Info Question 

### ISSUE THREAD

**Issue by phortonssf** [lazytanuki/nvim-mapper#17]
Given the following definition
`    Mapper.map_virtual("o", "af", "", {}, "Navigation", "treesitter_function_outer", "Function outer motion")
`

In the last part:
`"Navigation", "treesitter_function_outer", "Function outer motion"`
What is the middle qoutation section, `treesitter_function_outer`? I see that the first string is for a category and the last is the action mapped to the key but what is the 2nd ty.

**Comment by lodisy** [comment]
That's the unique identifier.
