### ISSUE TITLE
Feature request: Add support for newer 'vim.keymap.set' Nvim API

### ISSUE THREAD

**Issue by Issafalcon** [lazytanuki/nvim-mapper#21]
I'm really enjoying using this plugins functionality!

I think it could really be boosted by adding in support for the latest `vim.keymap.set()` API, which allows the user to do something like this:

```
vim.keymap.set({ "i", "s" }, "<c-l>", function()
  if ls.choice_active() then
    ls.change_choice(1)
  end
end)
```
So, allowing two modes to be combined in one keymap, and inlining a function in place of the string cmd from the older `vim.api.nvim_set_keymap()`.

At the moment, in places where I do this in my config files, I haven't switched to using nvim-mapper for those bindings.

Obviously, you could keep backwards compatibility with the older API function, but I imagine that given the newer function has been around since Neovim 0.7.0, not many people are still using versions older than that.

Thanks!

**Comment by Issafalcon** [comment]
#22 - PR to support this

**Comment by lazytanuki** [comment]
#22 Merged
