### ISSUE TITLE
Nothing happens when executing ":Telescope mapper"

### ISSUE THREAD

**Issue by glyh** [lazytanuki/nvim-mapper#4]
Here's the minimal init.lua to reproduce:
```lua
require('packer').startup(
{function()
  -- Packer can manage itself
  use 'wbthomason/packer.nvim'
  use {  
    'nvim-telescope/telescope.nvim',
    requires = {{'nvim-lua/popup.nvim'}, {'nvim-lua/plenary.nvim'}}
  }
  use {
   "lazytanuki/nvim-mapper",
    config = function() require("nvim-mapper").setup{} end
  }
end, config={git={default_url_format="https://hub.fastgit.org/%s"}}})

Mapper = require("nvim-mapper")
Mapper.map('n', '<leader>P', ":MarkdownPreview<CR>", 
  {silent = true, noremap = true}, 
  "Markdown", "md_preview", "Display Markdown preview in Qutebrowser")
```

1. Cover init.lua with the given one 
2. install ripgrep via " sudo pacman -S ripgrep" on arch linux
3. update plugins via “:PackerInstall" in neovim
4. restart neovim
5. execute ":Telescope mapper", nothing happens

**Comment by glyh** [comment]
BTW, hub.fastgit.org is but a CDN for github.

**Comment by lazytanuki** [comment]
Hi !

I indeed forgot to mention in the README that you need to load the nvim-mapper plugin before telescope.nvim, and that you then need to call `require("telescope").load_extension("mapper")` after loading the telescope.nvim plugin, my bad !
I've updated the documentation.

Also, don't forget to call `:PackerCompile` !

Let me know if it works out for you.

Have a good day !

**Comment by glyh** [comment]
Yeah it works! Thanks a lot!
