### ISSUE TITLE
Enhancement: add word wrapping for Mapping details

### ISSUE THREAD

**Issue by glyh** [lazytanuki/nvim-mapper#5]
Great plugin XD! But there's still something we can improve: 

This is the current details window: 

![image](https://user-images.githubusercontent.com/12870742/127743026-18e4480d-c6cf-40b0-b7fb-f39abb3a7d3b.png)

As we can notice the words exceeds the border(options & definition), so it would be good if we can make them wraps.

**Comment by lazytanuki** [comment]
Hi and thanks for the suggestion !

I've just added that feature 😉

Have a good day !
