### ISSUE TITLE
default mapper_search_path does not match telescope_mappers_file

### ISSUE THREAD

**Issue by mppadding** [lazytanuki/nvim-mapper#6]
The default value for vim.g.mapper_search_path does not match the same directory as telescope_mappers_file path

This results in a timeout of the plenary.job call (utils.lua:39).

Proposed fix:
Either change telescope_mappers_file in utils.lua to match the default search path or vice versa.
Might also be a good idea to mention the default value (stdpath('data'))

**Comment by lazytanuki** [comment]
Hi and thanks for reporting this !

It was a useless remnant from earlier on, last commit just fixed it.

Have a good day !
