### ISSUE TITLE
Execute command when pressing enter

### ISSUE THREAD

**Issue by issadarkthing** [lazytanuki/nvim-mapper#7]
Is it possible to configure to change default behavior `<cr>` key? I want it to execute the command after finding them instead of jump to their definition in the file.

**Comment by issadarkthing** [comment]
I think I solved it myself by replacing the `attach_mappings` option.

Add the following code to the `lua/plugin/nvim-mapper.lua`
```lua
local M = {}

M.mapper = function ()
  require'telescope'.extensions.mapper.mapper({
    attach_mappings = function(prompt_bufnr)
      local actions = require('telescope.actions')
      local action_state = require('telescope.actions.state')
      actions.select_default:replace(function()
        local selection = action_state.get_selected_entry()
        local nvim_feedkeys = vim.api.nvim_feedkeys
        local nvim_replace_termcodes = vim.api.nvim_replace_termcodes
        local cmd_k = nvim_replace_termcodes(selection.keys, true, false, true)
        nvim_feedkeys(cmd_k, "t", true)
        return actions.close(prompt_bufnr)
      end)
      return true
    end,
  })
end

return M
```

And then in your `lua/mappings.lua` rebind the default nvim-mapper command (`<leader>MM`)
```lua
local Mapper = require('nvim-mapper')

Mapper.map('n', '<leader>MM', "<cmd>lua require'plugin/nvim-mapper'.mapper()<cr>", {noremap = true, silent = true}, "Telescope", "telescope_mapper_toggle", "Show mappings using Telescope")
```

Hopefully, this helps.

**Comment by NTBBloodbath** [comment]
Hey, could you think of making this a PR? I'm really interested in this functionality but I don't want to hold a fork and have to manually update it to the upstream. Also thank you so much for sharing this! :slightly_smiling_face:
