### ISSUE TITLE
meaning of unique_identifier

### ISSUE THREAD

**Issue by thugcee** [lazytanuki/nvim-mapper#9]
Hi,
what for is `unique_identifier` used (beside detecting collisions)? It's cumbersome for me to create them, can I use UUID for it?

**Comment by lazytanuki** [comment]
Hi !
This `unique_identifier` is what is used by ripgrep to find where the plugin was defined in the configuration files. Initially I used an automatic way that would find where the function is being called using some debug functions, but then it wouldn't work with `packer_compiled.lua`, so I went with this unique identifier. Of course, it can be whatever you want, as long is there are no collisions and that it's defined in the function call (i.e not passed via a variable).

**Comment by thugcee** [comment]
Thank you. Now i understand.

Probably you should add `--fixed-strings` here:
https://github.com/lazytanuki/nvim-mapper/blob/c602a070153cc3be9be85ba2e1927b0551ddffc2/lua/telescope/_extensions/mapper/utils.lua#L34

How frequently is this `rg` started? 
It would be nice to have an options to turn it off.

**Comment by lazytanuki** [comment]
Ripgrep is only called once when invoking the Telescope and I can't use fixed strings because it uses a regex to find all the identifiers at once.

**Comment by thugcee** [comment]
Then it has to be as it is and I simply have to avoid regexp special chars in `unique_identifier` :)
I think we can close the case.
